apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green2-preview
  name: blue-green2-preview
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green2
  sessionAffinity: None
  type: ClusterIP
