apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green1-preview
    app.kubernetes.io/instance: blue-green1-preview
  name: blue-green1-preview
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green1
  sessionAffinity: None
  type: ClusterIP