apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: blue-green2
    app.kubernetes.io/instance: blue-green2
    release: blue-green2
  name: blue-green2
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: blue-green2
      release: blue-green2
  strategy:
    blueGreen:
      activeService: blue-green2
      previewService: blue-green2-preview
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue-green2
        release: blue-green
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: blue-green2
        ports:
        - containerPort: 80
          name: http
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
