apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: helm-guestbook
    app.kubernetes.io/instance: blue-green
    chart: helm-guestbook-0.1.0
    heritage: Tiller
    release: blue-green
  name: blue-green-helm-guestbook
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: blue-green
  strategy:
    blueGreen:
      activeService: blue-green-helm-guestbook
      previewService: blue-green-helm-guestbook-preview
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm-guestbook
        release: blue-green
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: helm-guestbook1
        ports:
        - containerPort: 80
          name: http
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
